In [ ]:
# pull in sheet
# go through tabs

# go through folders
# grab data in df

In [1]:
import pandas as pd
import os

In [22]:
df1 = pd.read_csv("c:\\users\\robert\\jupyter\\texas_2036\\indicators\\health\\Average number of physically unhealthy days within the last 30 days reported by adults\\state data\\state_data_Frequent Physical Distress.csv")
statecol = df1['State Name'].tolist()
statecol
df1.set_index("State Name", inplace=True)
df1.sort_values(by=['Value_2020'], ascending=True, inplace=True) 
df1

#x = df1.index.get_loc("Texas")
#print(x)

                      Unnamed: 0  Value_2019  Rank_2019  Value_2020  Rank_2020
State Name
District of Columbia          50         8.8        NaN         9.2        NaN
North Dakota                  33         9.8        3.0         9.3        1.0
Alaska                         1        12.0       23.0         9.8        2.0
Iowa                          14         9.6        1.0         9.9        3.0
Minnesota                     22         9.8        3.0         9.9        3.0
Maryland                      19        10.5        8.0        10.0        5.0
Colorado                       5         9.8        3.0        10.0        5.0
Nebraska                      26        10.2        6.0        10.4        7.0
Massachusetts                 20        11.4       16.0        10.5        8.0
Connecticut                    6        10.5        8.0        10.6        9.0
Hawaii                        10        10.5        8.0        10.6        9.0
Utah                          43        10.3        7.0        10.7       11.0
South Dakota                  40         9.6        1.0        10.8       12.0
Texas                         42        11.8       19.0        10.9       13.0
Wisconsin                     48        12.0       23.0        11.3       14.0
Illinois                      12        11.0       11.0        11.5       15.0
Kansas                        15        11.5       17.0        11.6       16.0
California                     4        12.2       27.0        11.6       16.0
Virginia                      45        11.1       12.0        11.7       18.0
New York                      31        11.2       13.0        11.7       18.0
Wyoming                       49        11.2       13.0        11.8       20.0
New Jersey                    29        11.9       21.0        11.9       21.0
Washington                    46        11.8       19.0        12.2       22.0
Vermont                       44        12.0       23.0        12.3       23.0
Oregon                        36        15.6       47.0        12.4       24.0
Delaware                       7        12.1       26.0        12.5       25.0
United States                 51        12.0        NaN        12.5        NaN
North Carolina                32        12.2       27.0        12.7       26.0
Idaho                         11        11.5       17.0        12.9       27.0
Rhode Island                  38        12.7       29.0        13.0       28.0
New Hampshire                 28        11.3       15.0        13.0       28.0
Pennsylvania                  37        12.9       31.0        13.0       28.0
Arizona                        2        14.2       38.0        13.2       31.0
Georgia                        9        12.7       29.0        13.3       32.0
Missouri                      24        13.8       36.0        13.3       32.0
Montana                       25        11.9       21.0        13.4       34.0
South Carolina                39        13.2       34.0        13.5       35.0
Indiana                       13        13.0       32.0        13.8       36.0
Florida                        8        13.8       36.0        13.8       36.0
Ohio                          34        13.1       33.0        13.9       38.0
Michigan                      21        14.3       40.0        13.9       38.0
Mississippi                   23        15.4       46.0        14.0       40.0
Maine                         18        13.7       35.0        14.0       40.0
Nevada                        27        14.5       41.0        14.2       42.0
New Mexico                    30        14.5       41.0        14.4       43.0
Oklahoma                      35        14.9       43.0        14.8       44.0
Louisiana                     17        14.2       38.0        14.9       45.0
Tennessee                     41        16.0       48.0        15.1       46.0
Alabama                        0        15.1       44.0        16.0       47.0
Kentucky                      16        15.3       45.0        16.6       48.0
Arkansas                       3        16.1       49.0        17.4       49.0
West Virginia                 47        19.2       50.0        19.0       50.0

In [7]:
folders = os.listdir("c:\\users\\robert\\jupyter\\texas_2036\\indicators")
my_csv=[]

peer_states=[
'Texas',
'California', 
'Colorado', 
'Florida', 
'Georgia', 
'Illinois', 
'New York', 
'North Carolina',
'Ohio', 
'Pennsylvania', 
'Virginia', 
'Washington'
]

# indicator, year,rank,peer_rank,previous_year,previous_peer_rank,previous_rank

# column_name
lister=[]

for f in folders:
    if ".git" in f:
        x=[]
    else:
        if os.path.isdir(os.path.join("c:\\users\\robert\\jupyter\\texas_2036\\indicators",f))==True:
            indicators = os.listdir(os.path.join("c:\\users\\robert\\jupyter\\texas_2036\\indicators",f))
            for i in indicators:
                ind_files = os.listdir(os.path.join("c:\\users\\robert\\jupyter\\texas_2036\\indicators",f, i))
                for d in ind_files:
                    if d=="state data":
                        state_data_files = os.listdir(os.path.join("c:\\users\\robert\\jupyter\\texas_2036\\indicators",f, i,d))
                        if len(state_data_files)>0:
                            #print(i)
                            for s in state_data_files:
                                df = pd.read_csv(os.path.join("c:\\users\\robert\\jupyter\\texas_2036\\indicators",f, i,d,s))
                                df_columns = df.columns.tolist()
                                years=[]
                                value_columns=[]
                                for j in df_columns:
                                    if "Value_" in j:
                                        # this_year = int(j.split('_')[1])
                                        # years.append(this_year)
                                        value_columns.append(j)
                                if "State" in df.columns:
                                    df["State"]=df["State"].str.strip()
                                    df.set_index("State", inplace=True)
                                    for v in value_columns:
                                        if v in df.columns:
                                            try:
                                                df.sort_values(by=[v], ascending=True, inplace=True) 
                                                x=df.index.get_loc("Texas") 
                                                peer_df=df[df.index.isin(peer_states)]
                                                peer_df.reset_index(inplace=True)
                                                peer_df.set_index("State", inplace=True)
                                                peer_df.sort_values(by=[v], ascending=True, inplace=True) 
                                                z=peer_df.index.get_loc("Texas")
                                                this_value = df.iloc[x][v]
                                                #print(i + "|"+ v +"|"+ str(x) + "|"+str(z))
                                                lister.append(i + "|"+ v +"|"+ str(this_value) +"|"+ str(x) + "|"+str(z))
                                            except:
                                                print("didnt: " +i)

C:\Users\Robert\Anaconda3\lib\site-packages\ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [8]:
file1=open("c:\\users\\robert\\desktop\\ranks_3.txt","w")
for l in lister:
    file1.write(l+"\n")
file1.close()

In [7]:
def abbr(state_list):
    if "Texas" in state_list:
        return "abbr"
    elif "TX" in state_list:
        return "fullname"

In [ ]:
#                                 value_columns=[]
#                                 state_column=""
#                                 name_type=""
#                                 for c in df_columns:
#                                     if "state" in c.lower():
#                                         state_column=c
#                                     elif "value" in c.lower():
#                                         value_columns.append(c)
#                                 #print(df[state_column].tolist())
#                                 if "TX" in df[state_column].tolist():
#                                     name_type="abbr"
#                                 elif "Texas" in df[state_column].tolist():
#                                     name_type= "fullname"
#                                 if name_type=="abbr": 
#                                     row = df[df[state_column]=="TX"]
#                                     print(row)         
#                                 elif name_type=="fullname":
#                                     row = df[df[state_column]=="TX"]
#                                     print(row)
#                                 #print(i + "|" + state_column)
#                                 #print(value_columns)

#                                 # if len(value_columns)>0:
#                                 #     for v in value_columns:
#                                 #         try: 
#                                 #             if name_type=="abbr": 
#                                 #                 print(df.loc["TX"])
#                                 #                 #z = df[state_column].get_loc("TX")
#                                 #                 #print(i + "|"+ z)
#                                 #             elif name_type=="fullname":
#                                 #                 print(df.loc["Texas"])
#                                 #                 # z = df.index.get_loc("Texas")
#                                 #                 # print(i + "|"+ z)
#                                 #         except:
#                                 #             print("didn't get :"+i)

#                                             #print(i + "|"+ df[df[state_column] == 'Texas'].index)

#                                             #z = df.index.get_loc("TX")
#                                             #print(i + "|"+ z)
#                                             #print(i + "|"+ df[df[state_column] == 'TX'].index)
                            

#                                 # get columns
#                                 # get state column
#                                 # sort values
# #df.set_index(state_column, inplace=True)
# #df.sort_values(by=[v], ascending=True, inplace=True) 
# #print(df[state_column].loc["TX"])



                                       # row = df[df['State']=="Texas"]
                                        # print(row)
                                #     df.set_index("State", inplace=True)
                                #     row = df[df['State']=="Texas"]